esphome:
  name: "ha-proxy-lcd"
  friendly_name: "HA Proxy LCD"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

sensor:
  - platform: homeassistant
    id: current_temp
    entity_id: sensor.h5179_004a_temperature
    internal: true

display:
  - platform: lcd_gpio
    dimensions: 16x2
    data_pins:
      - GPIO33
      - GPIO32
      - GPIO27
      - GPIO14
    enable_pin: GPIO25
    rs_pin: GPIO26
    lambda: |-
      it.print(0, 0, "Temp:");
      if (id(current_temp).has_state()) {
        it.printf(6, 0, "%.1f C", id(current_temp).state);
      } else {
        it.print(6, 0, "Wait...");
      }
