esphome:
  name: "ha-proxy-128x64"
  friendly_name: "HA Proxy 128x64"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Standard Logger
logger:

# API allows HA to talk to the ESP32
api:
  encryption:
    key: !secret api_key

# OTA allows wireless updates
ota:
  - platform: esphome
    password: !secret api_key

wifi:
  # !!! CHANGE THESE !!!
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Fallback in case wifi fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

# ==========================================
# 1. BLUETOOTH PROXY CONFIGURATION
# ==========================================
esp32_ble_tracker:
  scan_parameters:
    # "Active" scanning is better for battery sensors like Govee
    active: true

bluetooth_proxy:
  active: true

globals:
  - id: last_temp_update
    type: time_t
    restore_value: no
    initial_value: '0'

# ==========================================
# 2. DISPLAY CONFIGURATION
# ==========================================

# I2C Bus (Connect screen here)
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

# Font Setup
font:
  - file: "gfonts://Roboto"
    id: roboto_12
    size: 12
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20

# Time Component (for clock)
time:
  - platform: sntp
    id: sntp_time
    timezone: "America/New_York" # Change to your timezone

# Text Sensor for Trend
text_sensor:
  - platform: homeassistant
    id: temp_trend_status
    entity_id: sensor.green_house_temperature_status
    internal: true

# Import Sensor from Home Assistant
sensor:
  - platform: homeassistant
    id: current_temp
    entity_id: sensor.h5179_004a_temperature
    internal: true 
    on_value:
      then:
        - lambda: 'id(last_temp_update) = id(sntp_time).now().timestamp;' 

  - platform: homeassistant
    id: current_humidity
    entity_id: sensor.h5179_004a_humidity
    internal: true

  # Weather Temperature from Home Assistant
  - platform: homeassistant
    id: weather_temp
    entity_id: weather.forecast_home # Replace with your weather entity
    attribute: temperature
    internal: true

  # Temperature Derivative from Home Assistant
  - platform: homeassistant
    id: temp_derivative
    entity_id: sensor.green_house_temperature_derivative
    internal: true

  # Extra sensors for the status page
  - platform: uptime
    id: uptime_sensor
    update_interval: 60s

# Interval to switch pages every 5 seconds
interval:
  - interval: 5s
    then:
      - display.page.show_next: my_display
      - component.update: my_display

# Screen Setup
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    i2c_id: bus_a
    id: my_display
    contrast: 20% # Low brightness to save power
    
    pages:
      - id: page_temp
        lambda: |-
          // Header
          it.print(64, 0, id(roboto_12), TextAlign::TOP_CENTER, "GH Temperature");
          
          // Value
          if (id(current_temp).has_state()) {
            it.printf(64, 15, id(roboto_20), TextAlign::TOP_CENTER, "%.1f C", id(current_temp).state);
          } else {
            it.print(64, 15, id(roboto_20), TextAlign::TOP_CENTER, "--.-");
          }

          // Trend & Derivative
          if (id(temp_trend_status).has_state() && id(temp_derivative).has_state()) {
             it.printf(64, 38, id(roboto_12), TextAlign::TOP_CENTER, "%s (%.1f C/h)", id(temp_trend_status).state.c_str(), id(temp_derivative).state);
          } else if (id(temp_trend_status).has_state()) {
             it.printf(64, 38, id(roboto_12), TextAlign::TOP_CENTER, "%s", id(temp_trend_status).state.c_str());
          } else {
             it.print(64, 38, id(roboto_12), TextAlign::TOP_CENTER, "No Data");
          }
          
          // Footer (Page indicator)
          it.print(64, 54, id(roboto_12), TextAlign::TOP_CENTER, ". o o o o");

      - id: page_humidity
        lambda: |-
          // Header
          it.print(64, 0, id(roboto_12), TextAlign::TOP_CENTER, "GH Humidity");
          
          // Value
          if (id(current_humidity).has_state()) {
            it.printf(64, 25, id(roboto_20), TextAlign::TOP_CENTER, "%.1f %%", id(current_humidity).state);
          } else {
            it.print(64, 25, id(roboto_20), TextAlign::TOP_CENTER, "--.-");
          }
          
          // Footer (Page indicator)
          it.print(64, 52, id(roboto_12), TextAlign::TOP_CENTER, "o . o o o");

      - id: page_weather
        lambda: |-
          // Header
          it.print(64, 0, id(roboto_12), TextAlign::TOP_CENTER, "Outside");
          
          // Value
          if (id(weather_temp).has_state()) {
            it.printf(64, 25, id(roboto_20), TextAlign::TOP_CENTER, "%.1f C", id(weather_temp).state);
          } else {
            it.print(64, 25, id(roboto_20), TextAlign::TOP_CENTER, "--.-");
          }
          
          // Footer (Page indicator)
          it.print(64, 52, id(roboto_12), TextAlign::TOP_CENTER, "o o . o o");

      - id: page_clock
        lambda: |-
          // Header
          it.print(64, 0, id(roboto_12), TextAlign::TOP_CENTER, "Current Time");
          
          // Value
          it.strftime(64, 25, id(roboto_20), TextAlign::TOP_CENTER, "%I:%M %p", id(sntp_time).now());
          
          // Footer (Page indicator)
          it.print(64, 52, id(roboto_12), TextAlign::TOP_CENTER, "o o o . o");

      - id: page_info
        lambda: |-
          // Header
          it.print(64, 0, id(roboto_12), TextAlign::TOP_CENTER, "Status");
          
          // Value - Time since last temp update
          time_t now = id(sntp_time).now().timestamp;
          if (id(last_temp_update) == 0) {
             it.print(64, 20, id(roboto_12), TextAlign::TOP_CENTER, "Temp: No Data");
          } else {
             int diff = (int)(now - id(last_temp_update));
             if (diff < 60) {
                it.printf(64, 20, id(roboto_12), TextAlign::TOP_CENTER, "Temp: %ds ago", diff);
             } else {
                it.printf(64, 20, id(roboto_12), TextAlign::TOP_CENTER, "Temp: %dm ago", diff / 60);
             }
          }
          
          it.printf(64, 35, id(roboto_12), TextAlign::TOP_CENTER, "Uptime: %.0fs", id(uptime_sensor).state);

          // Footer (Page indicator)
          it.print(64, 52, id(roboto_12), TextAlign::TOP_CENTER, "o o o o .");
